import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DIRECT_URL! });
const prisma = new PrismaClient({ adapter });
type CategoriaType = "medicamento" | "alimento" | "accesorio" | "ropa";
type UrgenciaType = "alta" | "media" | "baja";

const productos: {
  nombre: string;
  descripcion: string;
  categoria: CategoriaType;
  precio: number;
  imagen: string;
  stock: number;
  disponible: boolean;
  urgencia: UrgenciaType;
}[] = [
  // ── MEDICAMENTOS (18) ──────────────────────────────────────────────────────
  {
    nombre: "Frontline Plus Antipulgas Perros Grandes",
    descripcion: "Tratamiento antipulgas y garrapatas para perros de 20-40kg. Protección por 30 días.",
    categoria: "medicamento",
    precio: 65.90,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 24,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Nexgard Antiparasitario Masticable",
    descripcion: "Comprimido masticable mensual contra pulgas y garrapatas. Sabor a res, fácil administración.",
    categoria: "medicamento",
    precio: 58.50,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 18,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Bravecto Antipulgas 3 Meses",
    descripcion: "Una sola dosis protege por 3 meses contra pulgas y garrapatas. Para perros 10-20kg.",
    categoria: "medicamento",
    precio: 89.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 12,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Advocate Pipeta Antiparasitaria",
    descripcion: "Pipeta spot-on contra pulgas, ácaros y parásitos internos. Ideal para perros pequeños hasta 4kg.",
    categoria: "medicamento",
    precio: 42.00,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 30,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Drontal Plus Desparasitante Interno",
    descripcion: "Tabletas desparasitantes de amplio espectro. Elimina lombrices, tenias y áscaris.",
    categoria: "medicamento",
    precio: 28.90,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 45,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Meloxicam Veterinario 1mg/ml",
    descripcion: "Antiinflamatorio y analgésico para perros. Alivio del dolor articular y post-quirúrgico.",
    categoria: "medicamento",
    precio: 35.00,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 20,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Suplemento Omega 3 para Mascotas",
    descripcion: "Cápsulas de aceite de salmón. Mejora pelaje, piel y articulaciones. 60 cápsulas.",
    categoria: "medicamento",
    precio: 32.50,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 38,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Vetmedin Corazón Canino 2.5mg",
    descripcion: "Medicamento cardíaco para perros con insuficiencia cardíaca. Presentación de 50 tabletas.",
    categoria: "medicamento",
    precio: 120.00,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 8,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Otoclean Limpiador de Oídos",
    descripcion: "Solución limpiadora auricular para perros y gatos. Previene otitis e infecciones.",
    categoria: "medicamento",
    precio: 22.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 25,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Cosequin DS Suplemento Articular",
    descripcion: "Glucosamina y condroitina para articulaciones. Ideal para perros mayores con artritis.",
    categoria: "medicamento",
    precio: 75.00,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 15,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Probiótico Fortiflora Canino",
    descripcion: "Suplemento probiótico para equilibrar la flora intestinal. Sobres individuales x30.",
    categoria: "medicamento",
    precio: 45.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 22,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Tramadol Veterinario 50mg",
    descripcion: "Analgésico opioide para dolor moderado a severo en perros. Requiere prescripción.",
    categoria: "medicamento",
    precio: 18.50,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 10,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Ciprofloxacino Veterinario 250mg",
    descripcion: "Antibiótico de amplio espectro para infecciones bacterianas en perros. 20 tabletas.",
    categoria: "medicamento",
    precio: 25.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 16,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Vitaminas B Complex Canino",
    descripcion: "Complejo vitamínico B para perros. Energía, sistema nervioso y metabolismo saludable.",
    categoria: "medicamento",
    precio: 19.90,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 40,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Apoquel Antialérgico 16mg",
    descripcion: "Tratamiento para el prurito asociado a dermatitis alérgica. Alivio en 4 horas.",
    categoria: "medicamento",
    precio: 95.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 7,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Shampoo Medicado Malaseb",
    descripcion: "Shampoo antifúngico y antibacteriano para dermatitis, sarna y hongos. 250ml.",
    categoria: "medicamento",
    precio: 38.00,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 19,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Suero Oral Rehidratante Canino",
    descripcion: "Rehidratación rápida para perros con vómitos o diarrea. Sabor pollo. 500ml.",
    categoria: "medicamento",
    precio: 15.00,
    imagen: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80",
    stock: 33,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Calmivet Ansiolítico Natural",
    descripcion: "Comprimidos calmantes con valeriana y melatonina. Para viajes, tormentas y estrés.",
    categoria: "medicamento",
    precio: 29.90,
    imagen: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=600&q=80",
    stock: 28,
    disponible: true,
    urgencia: "baja",
  },

  // ── ALIMENTOS (18) ─────────────────────────────────────────────────────────
  {
    nombre: "Royal Canin Adult Medium 15kg",
    descripcion: "Alimento balanceado para perros adultos de razas medianas. Protege el sistema digestivo.",
    categoria: "alimento",
    precio: 185.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 14,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Hills Science Diet Adulto 12kg",
    descripcion: "Nutrición precisa con ingredientes de calidad. Para perros adultos de 1-6 años.",
    categoria: "alimento",
    precio: 165.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 11,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Purina Pro Plan Cachorro 3kg",
    descripcion: "Fórmula con pollo y arroz para cachorros. DHA para desarrollo cerebral óptimo.",
    categoria: "alimento",
    precio: 72.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 20,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Eukanuba Senior Large Breed 12kg",
    descripcion: "Alimento para perros senior de razas grandes. Glucosamina para articulaciones.",
    categoria: "alimento",
    precio: 155.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 9,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Acana Grain Free Pollo 6kg",
    descripcion: "Alimento sin granos con 70% de ingredientes de origen animal. Perros activos.",
    categoria: "alimento",
    precio: 135.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 6,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Snacks Dentales Pedigree DentaStix",
    descripcion: "Palitos dentales que reducen el sarro en un 80%. Sabor original. Pack x28.",
    categoria: "alimento",
    precio: 28.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 50,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Alimento Húmedo Cesar Pollo x12",
    descripcion: "Bandejas de alimento húmedo gourmet para perros pequeños. Pack de 12 unidades.",
    categoria: "alimento",
    precio: 42.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 35,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Brit Care Lamb & Rice 12kg",
    descripcion: "Alimento premium con cordero y arroz. Sin gluten, ideal para perros sensibles.",
    categoria: "alimento",
    precio: 148.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 13,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Snacks Naturales Liofilizados Pollo",
    descripcion: "Trozos de pechuga de pollo liofilizados. 100% natural, sin aditivos. 100g.",
    categoria: "alimento",
    precio: 22.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 42,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Royal Canin Dermacomfort 10kg",
    descripcion: "Para perros con piel sensible e irritaciones. Reduce el picor desde la primera semana.",
    categoria: "alimento",
    precio: 145.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 8,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Orijen Original Dog 2kg",
    descripcion: "85% de proteína animal. Biológicamente apropiado. Pollo, pavo y huevo de corral.",
    categoria: "alimento",
    precio: 98.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 5,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Pasta de Maní para Perros 300g",
    descripcion: "Mantequilla de maní especial para mascotas. Sin xilitol. Perfecta para Kong y premios.",
    categoria: "alimento",
    precio: 18.90,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 60,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Hills Prescription Diet i/d 3.8kg",
    descripcion: "Dieta gastrointestinal veterinaria. Para perros con problemas digestivos crónicos.",
    categoria: "alimento",
    precio: 88.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 10,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Huesos Naturales Prensados x5",
    descripcion: "Huesos prensados de cuero natural para masticar. Limpieza dental y entretenimiento.",
    categoria: "alimento",
    precio: 25.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 45,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Purina ONE Senior 7+ años 3kg",
    descripcion: "Fórmula específica para perros mayores de 7 años. Omega 3, antioxidantes y glucosamina.",
    categoria: "alimento",
    precio: 68.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 17,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Caldo de Hueso Natural Perros 500ml",
    descripcion: "Caldo 100% natural de huesos de res. Hidratación extra y nutrientes esenciales.",
    categoria: "alimento",
    precio: 16.50,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 30,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Zignature Trucha y Salmón 12.5kg",
    descripcion: "Alimento hipoalergénico con una sola fuente de proteína. Sin pollo, maíz ni soya.",
    categoria: "alimento",
    precio: 210.00,
    imagen: "https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?w=600&q=80",
    stock: 4,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Snacks Entrenamiento Zukes Mini 170g",
    descripcion: "Premios suaves de 3 calorías para entrenamiento. Sabor salmón. Bolsa resellable.",
    categoria: "alimento",
    precio: 32.00,
    imagen: "https://images.unsplash.com/photo-1601758125946-6ec2ef64daf8?w=600&q=80",
    stock: 38,
    disponible: true,
    urgencia: "baja",
  },

  // ── ACCESORIOS (14) ────────────────────────────────────────────────────────
  {
    nombre: "Cama Ortopédica Memory Foam L",
    descripcion: "Cama con espuma viscoelástica para perros grandes. Funda lavable. 90x70cm.",
    categoria: "accesorio",
    precio: 189.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 7,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Correa Retráctil Premium 5 metros",
    descripcion: "Correa extensible con freno de seguridad. Hasta 50kg. Mango ergonómico antideslizante.",
    categoria: "accesorio",
    precio: 55.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 22,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Arnés Antitirones Step-in Talla M",
    descripcion: "Arnés con clip frontal y dorsal que reduce el tirón. Acolchado en zonas de contacto.",
    categoria: "accesorio",
    precio: 72.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 15,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Bebedero Automático con Filtro 3L",
    descripcion: "Fuente de agua con filtro de carbón activo. Silenciosa, circulación continua de agua fresca.",
    categoria: "accesorio",
    precio: 95.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 11,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Transportín Aéreo IATA Talla S",
    descripcion: "Transportín aprobado para cabina de avión. Ventilación lateral. Para perros hasta 6kg.",
    categoria: "accesorio",
    precio: 145.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 5,
    disponible: true,
    urgencia: "alta",
  },
  {
    nombre: "Juguete Kong Classic Talla L",
    descripcion: "Juguete rellenable de goma natural resistente. Estimulación mental y alivio del estrés.",
    categoria: "accesorio",
    precio: 48.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 28,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Collar GPS Tractive Perros",
    descripcion: "Localizador GPS en tiempo real con historial de rutas. Resistente al agua. App incluida.",
    categoria: "accesorio",
    precio: 320.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 4,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Cepillo Furminator Perros Medios",
    descripcion: "Deslanador profesional que elimina el 90% del pelo muerto sin dañar la capa superior.",
    categoria: "accesorio",
    precio: 85.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 13,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Plato Antitragón Acero Inoxidable",
    descripcion: "Comedero con laberinto que reduce la velocidad de ingesta. Previene el síndrome gástrico.",
    categoria: "accesorio",
    precio: 32.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 24,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Mochila Transportadora Perros 6kg",
    descripcion: "Mochila con ventanas de malla para llevar a tu perro. Cómoda para ambos. Hasta 6kg.",
    categoria: "accesorio",
    precio: 120.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 8,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Juguete Snuffle Mat Olfativo",
    descripcion: "Alfombra de olfateo para estimulación mental. Esconde premios entre las fibras. Lavable.",
    categoria: "accesorio",
    precio: 55.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 16,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Cinturón Seguridad Auto Perros M",
    descripcion: "Arnés homologado para viajes en auto. Se conecta al cinturón de seguridad. Talla M.",
    categoria: "accesorio",
    precio: 42.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-45d0a4d3e407?w=600&q=80",
    stock: 20,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Piscina Plegable Perros XL 160cm",
    descripcion: "Piscina portátil de PVC resistente para perros grandes. Fácil de llenar y vaciar. 160cm.",
    categoria: "accesorio",
    precio: 78.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 9,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Kit Dental Perros (cepillo + pasta)",
    descripcion: "Cepillo de silicona para dedo + pasta dental sabor pollo sin flúor. Previene sarro y mal aliento. Para todas las razas.",
    categoria: "accesorio",
    precio: 19.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=600&q=80",
    stock: 20,
    disponible: true,
    urgencia: "media",
  },

  // ── ROPA Y MODA CANINA (15) ────────────────────────────────────────────────
  {
    nombre: "Polera Adidog Roja Talla M",
    descripcion: "Polera deportiva estilo urbano con capucha y tela polar suave. Mantiene el calor en climas fríos y brinda máxima comodidad. Ideal para perros medianos.",
    categoria: "ropa",
    precio: 39.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 18,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Casaca Impermeable Reflectiva Talla L",
    descripcion: "Chaqueta impermeable con bandas reflectivas para paseos nocturnos. Interior acolchado y cierre ajustable. Protege del frío y la lluvia.",
    categoria: "ropa",
    precio: 58.00,
    imagen: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&q=80",
    stock: 10,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Pijama Polar Estrellitas Talla S",
    descripcion: "Pijama térmico ultra suave para noches frías. Diseño adorable con estampado de estrellas y ajuste cómodo para dormir tranquilo.",
    categoria: "ropa",
    precio: 32.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 15,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Vestido Princesa Rosado",
    descripcion: "Vestido elegante con falda de tul y lazo brillante. Perfecto para cumpleaños, sesiones de fotos y eventos especiales.",
    categoria: "ropa",
    precio: 49.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 9,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Traje Formal Smoking Negro",
    descripcion: "Elegante traje tipo smoking con camisa y corbatín incorporado. Ideal para bodas, fiestas y ocasiones especiales.",
    categoria: "ropa",
    precio: 65.00,
    imagen: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80",
    stock: 7,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Buzo Deportivo Azul Marino",
    descripcion: "Buzo deportivo cómodo y flexible para paseos o entrenamiento. Tela respirable y costuras reforzadas. Diseño moderno.",
    categoria: "ropa",
    precio: 42.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-e3b965d5edbb?w=500&q=80",
    stock: 16,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Chaleco de Invierno Acolchado",
    descripcion: "Chaleco térmico acolchado con cierre de velcro. Ligero pero muy cálido. Perfecto para razas pequeñas y medianas.",
    categoria: "ropa",
    precio: 44.50,
    imagen: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&q=80",
    stock: 13,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Bandana Fashion Tropical",
    descripcion: "Bandana ligera con estampado tropical colorido. Ajustable y fresca para verano. Dale estilo único a tu mascota.",
    categoria: "ropa",
    precio: 14.00,
    imagen: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=500&q=80",
    stock: 25,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Gorro Navideño para Perros",
    descripcion: "Gorro suave estilo Santa Claus con ajuste elástico cómodo. Accesorio perfecto para fotos navideñas y fiestas.",
    categoria: "ropa",
    precio: 18.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 20,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Sudadera StreetWear Negra",
    descripcion: "Sudadera urbana premium con capucha y estampado moderno. Tela suave tipo algodón fleece. Look moderno y cómodo.",
    categoria: "ropa",
    precio: 47.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-e3b965d5edbb?w=500&q=80",
    stock: 12,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Botitas Antideslizantes x4",
    descripcion: "Zapatos protectores para lluvia, tierra caliente o nieve. Suela antideslizante y ajuste con velcro resistente.",
    categoria: "ropa",
    precio: 36.00,
    imagen: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=500&q=80",
    stock: 14,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Camisa Hawaiiana Verano",
    descripcion: "Camisa fresca estilo hawaiano con botones y estampado floral. Ideal para verano, playa y sesiones de fotos.",
    categoria: "ropa",
    precio: 29.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 17,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Poncho Andino para Mascotas",
    descripcion: "Poncho artesanal inspirado en diseños andinos peruanos. Tejido cálido y cómodo para días fríos.",
    categoria: "ropa",
    precio: 52.00,
    imagen: "https://images.unsplash.com/photo-1601758174493-e3b965d5edbb?w=500&q=80",
    stock: 8,
    disponible: true,
    urgencia: "media",
  },
  {
    nombre: "Polo Básico Blanco Premium",
    descripcion: "Polo ligero y cómodo para uso diario. Tela transpirable de alta calidad y costuras resistentes.",
    categoria: "ropa",
    precio: 22.00,
    imagen: "https://images.unsplash.com/photo-1517849845537-4d257902454a?w=500&q=80",
    stock: 30,
    disponible: true,
    urgencia: "baja",
  },
  {
    nombre: "Disfraz de Dinosaurio Verde",
    descripcion: "Disfraz divertido con capucha y cola acolchada. Tela suave y cómoda para eventos, Halloween y fotos virales.",
    categoria: "ropa",
    precio: 55.00,
    imagen: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=500&q=80",
    stock: 6,
    disponible: true,
    urgencia: "baja",
  },
];

async function main() {
  console.log("🌱 Iniciando seed de productos Mimos Pet Club...\n");

  // Limpiar tablas relacionadas antes de productos
  await prisma.reservaItem.deleteMany();
  await prisma.reserva.deleteMany();
  await prisma.producto.deleteMany();
  console.log("🗑️  Productos anteriores eliminados\n");

  // Insertar todos los productos
  const result = await prisma.producto.createMany({
    data: productos,
  });

  const porCategoria = {
    medicamento: productos.filter((p) => p.categoria === "medicamento").length,
    alimento: productos.filter((p) => p.categoria === "alimento").length,
    accesorio: productos.filter((p) => p.categoria === "accesorio").length,
    ropa: productos.filter((p) => p.categoria === "ropa").length,
  };

  console.log(`🎉 Seed completado: ${result.count} productos creados`);
  console.log(`   💊 Medicamentos: ${porCategoria.medicamento}`);
  console.log(`   🍖 Alimentos:    ${porCategoria.alimento}`);
  console.log(`   🦮 Accesorios:   ${porCategoria.accesorio}`);
  console.log(`   👗 Ropa:         ${porCategoria.ropa}`);
}

main()
  .catch((e) => {
    console.error("❌ Error en seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });